package com.restaurant.infraestructura.persistencia;

import com.restaurant.aplicacion.puerto.salida.InventarioRepositorio;
import com.restaurant.dominio.inventario.Ingrediente;
import com.restaurant.dominio.inventario.MovimientoInventario;
import com.restaurant.dominio.inventario.Receta;
import com.restaurant.dominio.inventario.StockInsuficienteException;
import com.restaurant.dominio.inventario.TipoMovimiento;
import com.restaurant.dominio.inventario.UnidadMedida;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.TreeMap;

/**
 * Adaptador de salida del inventario sobre H2 (JDBC plano + pool).
 *
 * Cómo se garantiza que dos pedidos simultáneos no vendan el mismo último
 * ingrediente:
 *  1. Todo el descuento de un pedido va en UNA transacción.
 *  2. Cada ingrediente se descuenta con un UPDATE condicional
 *     "SET stock = stock - ? WHERE codigo = ? AND stock >= ?": la base de
 *     datos bloquea la fila y solo resta si alcanza. Si devuelve 0 filas,
 *     no alcanzó -> rollback de todo el pedido.
 *  3. Las filas se tocan en orden alfabético de código (TreeMap) para que
 *     dos transacciones no se esperen mutuamente (interbloqueo).
 *  4. CHECK (stock >= 0) en la tabla: segunda barrera si algún día alguien
 *     escribe un UPDATE sin la condición.
 * La prueba InventarioConcurrenciaIT y la prueba de carga lo verifican.
 */
public class InventarioRepositorioJdbc implements InventarioRepositorio {

    private final DataSource dataSource;

    public InventarioRepositorioJdbc(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    public void initSchema() {
        try (Connection con = dataSource.getConnection(); Statement st = con.createStatement()) {
            st.execute("CREATE TABLE IF NOT EXISTS ingrediente(" +
                    " codigo VARCHAR(40) PRIMARY KEY," +
                    " nombre VARCHAR(80) NOT NULL," +
                    " unidad VARCHAR(20) NOT NULL," +
                    " stock BIGINT NOT NULL," +
                    " stock_minimo BIGINT NOT NULL," +
                    " CONSTRAINT ck_stock_no_negativo CHECK (stock >= 0))");
            st.execute("CREATE TABLE IF NOT EXISTS receta(" +
                    " plato VARCHAR(80) NOT NULL," +
                    " ingrediente VARCHAR(40) NOT NULL," +
                    " cantidad BIGINT NOT NULL," +
                    " PRIMARY KEY (plato, ingrediente)," +
                    " FOREIGN KEY (ingrediente) REFERENCES ingrediente(codigo))");
            st.execute("CREATE TABLE IF NOT EXISTS movimiento_inventario(" +
                    " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    " fecha TIMESTAMP NOT NULL," +
                    " ingrediente VARCHAR(40) NOT NULL," +
                    " tipo VARCHAR(20) NOT NULL," +
                    " cantidad BIGINT NOT NULL," +
                    " stock_resultante BIGINT NOT NULL," +
                    " pedido_id INT," +
                    " descripcion VARCHAR(200)," +
                    " FOREIGN KEY (ingrediente) REFERENCES ingrediente(codigo))");
            st.execute("CREATE INDEX IF NOT EXISTS idx_mov_ingrediente ON movimiento_inventario(ingrediente, id)");
            st.execute("CREATE INDEX IF NOT EXISTS idx_mov_pedido ON movimiento_inventario(pedido_id)");
        } catch (SQLException e) {
            throw new ErrorPersistenciaException("No se pudo crear el esquema de inventario", e);
        }
    }

    // ------------------------------------------------------------------
    // Ingredientes y recetas
    // ------------------------------------------------------------------

    @Override
    public List<Ingrediente> listarIngredientes() {
        String sql = "SELECT codigo, nombre, unidad, stock, stock_minimo FROM ingrediente ORDER BY nombre";
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            List<Ingrediente> lista = new ArrayList<>();
            while (rs.next()) {
                lista.add(mapearIngrediente(rs));
            }
            return lista;
        } catch (SQLException e) {
            throw new ErrorPersistenciaException("No se pudo leer el inventario", e);
        }
    }

    @Override
    public Optional<Ingrediente> buscarIngrediente(String codigo) {
        String sql = "SELECT codigo, nombre, unidad, stock, stock_minimo FROM ingrediente WHERE codigo = ?";
        try (Connection con = dataSource.getConnection(); PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, codigo);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? Optional.of(mapearIngrediente(rs)) : Optional.empty();
            }
        } catch (SQLException e) {
            throw new ErrorPersistenciaException("No se pudo leer el ingrediente " + codigo, e);
        }
    }

    @Override
    public void guardarIngrediente(Ingrediente ing) {
        String update = "UPDATE ingrediente SET nombre = ?, unidad = ?, stock = ?, stock_minimo = ? WHERE codigo = ?";
        String insert = "INSERT INTO ingrediente(nombre, unidad, stock, stock_minimo, codigo) VALUES(?, ?, ?, ?, ?)";
        try (Connection con = dataSource.getConnection()) {
            int filas;
            try (PreparedStatement ps = con.prepareStatement(update)) {
                llenarIngrediente(ps, ing);
                filas = ps.executeUpdate();
            }
            if (filas == 0) {
                try (PreparedStatement ps = con.prepareStatement(insert)) {
                    llenarIngrediente(ps, ing);
                    ps.executeUpdate();
                }
            }
        } catch (SQLException e) {
            throw new ErrorPersistenciaException("No se pudo guardar el ingrediente " + ing.getCodigo(), e);
        }
    }

    @Override
    public Map<String, Receta> recetasPorPlato() {
        String sql = "SELECT plato, ingrediente, cantidad FROM receta ORDER BY plato, ingrediente";
        Map<String, Map<String, Long>> filas = new LinkedHashMap<>();
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                filas.computeIfAbsent(rs.getString("plato"), k -> new LinkedHashMap<>())
                        .put(rs.getString("ingrediente"), rs.getLong("cantidad"));
            }
        } catch (SQLException e) {
            throw new ErrorPersistenciaException("No se pudieron leer las recetas", e);
        }
        Map<String, Receta> recetas = new LinkedHashMap<>();
        filas.forEach((plato, ingredientes) -> recetas.put(plato, new Receta(plato, ingredientes)));
        return recetas;
    }

    @Override
    public void guardarReceta(Receta receta) {
        try (Connection con = dataSource.getConnection()) {
            con.setAutoCommit(false);
            try {
                try (PreparedStatement del = con.prepareStatement("DELETE FROM receta WHERE plato = ?")) {
                    del.setString(1, receta.getPlato());
                    del.executeUpdate();
                }
                try (PreparedStatement ins = con.prepareStatement(
                        "INSERT INTO receta(plato, ingrediente, cantidad) VALUES(?, ?, ?)")) {
                    for (Map.Entry<String, Long> e : receta.getPorPorcion().entrySet()) {
                        ins.setString(1, receta.getPlato());
                        ins.setString(2, e.getKey());
                        ins.setLong(3, e.getValue());
                        ins.addBatch();
                    }
                    ins.executeBatch();
                }
                con.commit();
            } catch (SQLException e) {
                con.rollback();
                throw e;
            } finally {
                con.setAutoCommit(true);
            }
        } catch (SQLException e) {
            throw new ErrorPersistenciaException("No se pudo guardar la receta de " + receta.getPlato(), e);
        }
    }

    // ------------------------------------------------------------------
    // Movimientos de stock (atómicos)
    // ------------------------------------------------------------------

    @Override
    public Map<String, Long> descontar(Map<String, Long> consumo, Motivo motivo) {
        Map<String, Long> ordenado = new TreeMap<>(consumo);
        try (Connection con = dataSource.getConnection()) {
            con.setAutoCommit(false);
            try {
                List<StockInsuficienteException.Faltante> faltantes = new ArrayList<>();
                for (Map.Entry<String, Long> e : ordenado.entrySet()) {
                    if (!restarSiAlcanza(con, e.getKey(), e.getValue())) {
                        faltantes.add(faltante(con, e.getKey(), e.getValue()));
                    }
                }
                if (!faltantes.isEmpty()) {
                    con.rollback();
                    throw new StockInsuficienteException(faltantes);
                }
                Map<String, Long> resultantes = registrar(con, ordenado, motivo);
                con.commit();
                return resultantes;
            } catch (SQLException | RuntimeException e) {
                con.rollback();
                throw e;
            } finally {
                con.setAutoCommit(true);
            }
        } catch (SQLException e) {
            throw new ErrorPersistenciaException("No se pudo descontar inventario", e);
        }
    }

    @Override
    public Map<String, Long> sumar(Map<String, Long> cantidades, Motivo motivo) {
        Map<String, Long> ordenado = new TreeMap<>(cantidades);
        try (Connection con = dataSource.getConnection()) {
            con.setAutoCommit(false);
            try {
                for (Map.Entry<String, Long> e : ordenado.entrySet()) {
                    try (PreparedStatement ps = con.prepareStatement(
                            "UPDATE ingrediente SET stock = stock + ? WHERE codigo = ?")) {
                        ps.setLong(1, e.getValue());
                        ps.setString(2, e.getKey());
                        if (ps.executeUpdate() == 0) {
                            throw new IllegalArgumentException("No existe el ingrediente " + e.getKey());
                        }
                    }
                }
                Map<String, Long> resultantes = registrar(con, ordenado, motivo);
                con.commit();
                return resultantes;
            } catch (SQLException | RuntimeException e) {
                con.rollback();
                throw e;
            } finally {
                con.setAutoCommit(true);
            }
        } catch (SQLException e) {
            throw new ErrorPersistenciaException("No se pudo sumar inventario", e);
        }
    }

    @Override
    public void registrarSinCambio(Map<String, Long> cantidades, Motivo motivo) {
        try (Connection con = dataSource.getConnection()) {
            con.setAutoCommit(false);
            try {
                registrar(con, new TreeMap<>(cantidades), motivo);
                con.commit();
            } catch (SQLException | RuntimeException e) {
                con.rollback();
                throw e;
            } finally {
                con.setAutoCommit(true);
            }
        } catch (SQLException e) {
            throw new ErrorPersistenciaException("No se pudo registrar la merma", e);
        }
    }

    @Override
    public List<MovimientoInventario> movimientos(String codigo, int limite) {
        String sql = "SELECT * FROM movimiento_inventario"
                + (codigo == null ? "" : " WHERE ingrediente = ?")
                + " ORDER BY id DESC LIMIT ?";
        try (Connection con = dataSource.getConnection(); PreparedStatement ps = con.prepareStatement(sql)) {
            int i = 1;
            if (codigo != null) {
                ps.setString(i++, codigo);
            }
            ps.setInt(i, limite);
            return leerMovimientos(ps);
        } catch (SQLException e) {
            throw new ErrorPersistenciaException("No se pudieron leer los movimientos", e);
        }
    }

    @Override
    public List<MovimientoInventario> movimientosDePedido(int pedidoId) {
        String sql = "SELECT * FROM movimiento_inventario WHERE pedido_id = ? ORDER BY id";
        try (Connection con = dataSource.getConnection(); PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1, pedidoId);
            return leerMovimientos(ps);
        } catch (SQLException e) {
            throw new ErrorPersistenciaException("No se pudieron leer los movimientos del pedido " + pedidoId, e);
        }
    }

    // ------------------------------------------------------------------

    private static boolean restarSiAlcanza(Connection con, String codigo, long cantidad) throws SQLException {
        try (PreparedStatement ps = con.prepareStatement(
                "UPDATE ingrediente SET stock = stock - ? WHERE codigo = ? AND stock >= ?")) {
            ps.setLong(1, cantidad);
            ps.setString(2, codigo);
            ps.setLong(3, cantidad);
            return ps.executeUpdate() == 1;
        }
    }

    private static StockInsuficienteException.Faltante faltante(Connection con, String codigo, long requerido)
            throws SQLException {
        try (PreparedStatement ps = con.prepareStatement(
                "SELECT nombre, unidad, stock FROM ingrediente WHERE codigo = ?")) {
            ps.setString(1, codigo);
            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) {
                    throw new IllegalArgumentException("La receta usa un ingrediente que no existe: " + codigo);
                }
                return new StockInsuficienteException.Faltante(codigo, rs.getString("nombre"), requerido,
                        rs.getLong("stock"), UnidadMedida.valueOf(rs.getString("unidad")));
            }
        }
    }

    /** Inserta un movimiento por ingrediente con el stock que quedó. */
    private static Map<String, Long> registrar(Connection con, Map<String, Long> cantidades, Motivo motivo)
            throws SQLException {
        Map<String, Long> resultantes = new LinkedHashMap<>();
        String sql = "INSERT INTO movimiento_inventario(fecha, ingrediente, tipo, cantidad, stock_resultante, "
                + "pedido_id, descripcion) VALUES(?, ?, ?, ?, ?, ?, ?)";
        try (PreparedStatement stock = con.prepareStatement("SELECT stock FROM ingrediente WHERE codigo = ?");
             PreparedStatement ins = con.prepareStatement(sql)) {
            for (Map.Entry<String, Long> e : cantidades.entrySet()) {
                stock.setString(1, e.getKey());
                long actual;
                try (ResultSet rs = stock.executeQuery()) {
                    if (!rs.next()) {
                        throw new IllegalArgumentException("No existe el ingrediente " + e.getKey());
                    }
                    actual = rs.getLong(1);
                }
                resultantes.put(e.getKey(), actual);
                ins.setObject(1, motivo.fecha());
                ins.setString(2, e.getKey());
                ins.setString(3, motivo.tipo().name());
                ins.setLong(4, e.getValue());
                ins.setLong(5, actual);
                if (motivo.pedidoId() == null) {
                    ins.setNull(6, Types.INTEGER);
                } else {
                    ins.setInt(6, motivo.pedidoId());
                }
                ins.setString(7, motivo.descripcion());
                ins.addBatch();
            }
            ins.executeBatch();
        }
        return resultantes;
    }

    private static List<MovimientoInventario> leerMovimientos(PreparedStatement ps) throws SQLException {
        List<MovimientoInventario> lista = new ArrayList<>();
        try (ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                Integer pedido = rs.getObject("pedido_id", Integer.class);
                lista.add(new MovimientoInventario(rs.getLong("id"),
                        rs.getObject("fecha", LocalDateTime.class), rs.getString("ingrediente"),
                        TipoMovimiento.valueOf(rs.getString("tipo")), rs.getLong("cantidad"),
                        rs.getLong("stock_resultante"), pedido, rs.getString("descripcion")));
            }
        }
        return lista;
    }

    private static void llenarIngrediente(PreparedStatement ps, Ingrediente ing) throws SQLException {
        ps.setString(1, ing.getNombre());
        ps.setString(2, ing.getUnidad().name());
        ps.setLong(3, ing.getStock());
        ps.setLong(4, ing.getStockMinimo());
        ps.setString(5, ing.getCodigo());
    }

    private static Ingrediente mapearIngrediente(ResultSet rs) throws SQLException {
        return new Ingrediente(rs.getString("codigo"), rs.getString("nombre"),
                UnidadMedida.valueOf(rs.getString("unidad")), rs.getLong("stock"), rs.getLong("stock_minimo"));
    }
}
